config/routes.rb
Why::Application.routes.draw do
  devise_for :customers
  devise_for :supplier_users
  devise_for :admins

  resources  :supplier_users
  resources :rounds do 
    member do
      get :past
      get :future
    end
    resources  :deliveries do
      collection do
        post :create_all
      end
    end
  end
  resources :products do
    collection do 
      post :reorder
      get :cat
    end
  end
  resources :customers do
    member do
      get :invite
    end
    resources :orders do
      collection do
        get :confirm
        get :past
      end
    end
  end

  resources :suppliers do
    member do
      get :switch
      post :accept
      post :download
      post :labels
    end
  end

  scope :path => '/home', :controller => :home do 
    match '/index'	=> :index, :as => "home" 
    match '/index2'	=> :index2 
    match '/how' => :how, :as => "how"
    match '/about' => :about, :as => "about"
    match '/price' => :price, :as => "price"
    match '/contact' => :contact, :as => "contact"
    match '/blog' => :blog, :as => "blog"
    match '/guide' => :guide, :as => "guide"
  end

  match '/embed', :controller => :home, :action => :embed
  
  constraints(Subdomain) do  
    match '/', :to => redirect("/customers/sign_in") 
  end  
  
  root :to => "home#index"
  match 'test/' => 'java_script_tests#order'

end

app/models/round.rb
class Round < ActiveRecord::Base
  belongs_to :supplier
  has_many :customers
  has_many :deliverys, :dependent => :destroy
  scope :for_supplier, lambda { |supplier_id|
    {:conditions => ["supplier_id = ?", supplier_id]}}

  before_destroy do |entry| 
    raise ActiveRecord::RecordNotDestroyed unless entry.destroyable?
  end
  
  def destroyable?
    self.customers.empty?
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_filter :authenticate_supplier!

  def index
    @rounds = Round.find_all_by_supplier_id(@supplier.id)
  end

  def new
    @round = Round.new
    render :action => 'edit'
  end

  def edit
    @round = Round.find(params[:id])
  end

  def create
    r = Round.create(params[:round].merge(:supplier_id => @supplier.id))
    redirect_to round_path(r)
  end

  def update
    r = Round.find(params[:id])
    r.update_attributes(params[:round])
    redirect_to rounds_path
  end

  def destroy
    round = Round.find(params[:id])
    flash[:alert] = "Round removed successfully"
    begin
      round.destroy
    rescue ActiveRecord::RecordNotDestroyed
      flash[:alert] = "You can't delete this round whilst there are customers on it"
    end
    redirect_to rounds_path
  end

  def past
    setup_show 'date < curdate()'
  end

  def future
    setup_show 'date >= curdate()'
  end

  def show
    setup_show nil
  end

  private

  def setup_show(conditions)
    @round = Round.find(params[:id])
    @deliveries = Delivery.find_all_by_round_id(params[:id], :order => 'date', :conditions => conditions) || []
    @delivery_months = @deliveries.group_by { |d| d.date.beginning_of_month }
    @days = Delivery.days
    render :action => 'show'
  end
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/rounds/edit.html.haml
%h1="#{controller.action_name.capitalize} Round"
=form_for @round do |r|
  .pairs
    %p.clear
      .left=r.label :name
      .right=r.text_field :name
    %p.clear
      .left=r.label :area
      .right=r.text_area :area, :rows => 3
    %p.clear
      .left=r.label :schedule
      .right=r.text_area :schedule, :rows => 3
    %p.clear
      .left=r.label :customer_message
      .right=r.text_area :customer_message, :rows => 3
    %p.clear
      .left
      .right=submit_tag

app/views/rounds/index.html.haml
#help
  %h2 Tasks
  %ul
    %li
      =link_to 'Create', new_round_path
      and edit new rounds
  %h2 Help
  %ul
    %li Once you have created a round you'll need to add deliveries to it, click the 'Add or Edit deliveries' and theres more help when you get there

%h1 Manage Your Rounds
%ul.boxes
  -@rounds.each do |r|
    %li
      .box
        %ul
          %li
            %h3=r.name
          %li=r.area
          %li=r.schedule
          %li=link_to 'Edit this round', edit_round_path(r)
          %li=link_to 'Add or Edit deliveries', round_path(r)
          %li=link_to 'Delete', r, :confirm => 'Are you sure you want to delete this round and all its deliveries. The round will not be deleted if it is used by any customers', :method => :delete

app/views/rounds/show.html.haml
#help
  %h2 Help
  %ul
    %li
      Here is where you can add and edit delivery dates for
      =@round.name
      \. Your schedule is 
      =@round.schedule
      \.
    %li
      We recomend you create deliveries for the rest of the year. Select the days for the round and the dates you want the deliveries to run to and hit the 'create delvieries' button. Once the dates are created you can edit them if they change for bank holidays and the like.
%h1 Deliveries for #{@round.name} Round
=form_tag(create_all_round_deliveries_path(@round.id)) do
  %fieldset.doubledecker
    %legend Add deliveries
    =hidden_field_tag :round, @round.id
    %ul
      %li
        %label.main{:for => "day_Monday"} Select delivery days:
        -@days.each do |i, day| 
          =label_tag "day_#{day}", day
          =check_box_tag "day[]", i, false, :id => "day_#{day}"
          &nbsp;
      %li
        %label{:for => 'from_day'} From:
        =select_date Time.now,:prefix => 'from', :order => [:day, :month, :year]
        %label{:for => 'to_day'} To:
        =select_date Time.now,:prefix => 'to', :order => [:day, :month, :year]
      %li
        %label.main Last orders may be made up to:
        =select "last_order", "day", 0..10
        day(s) before delivery at
        =select_hour 12, :field_name => 'last_order[hour]', :prefix => ''
        \:00
      %li
        =submit_tag 'Create Deliveries'
        or 
        =link_to 'create', new_round_delivery_path(@round)
        a single delivery
%h2 Current scheduled deliveries are:
%p 
  Show 
  =link_to 'All', round_path(@round)
  =link_to 'Past', past_round_path(@round)
  =link_to 'Future', future_round_path(@round)
  %br
  -@delivery_months.sort.each do |month, deliveries|
    %h3=month.strftime('%B %Y')
    -deliveries.each do |d|
      =link_to d.date.strftime("%A #{d.date.day.ordinalize}"), edit_round_delivery_path(@round,d)