config/routes.rb
Why::Application.routes.draw do
  devise_for :customers
  devise_for :supplier_users
  devise_for :admins

  resources  :supplier_users
  resources :rounds do 
    member do
      get :past
      get :future
    end
    resources  :deliveries do
      collection do
        post :create_all
      end
    end
  end
  resources :products do
    collection do 
      post :reorder
      get :cat
    end
  end
  resources :customers do
    member do
      get :invite
    end
    resources :orders do
      collection do
        get :confirm
        get :past
      end
    end
  end

  resources :suppliers do
    member do
      get :switch
      post :accept
      post :download
      post :labels
    end
  end

  scope :path => '/home', :controller => :home do 
    match '/index'	=> :index, :as => "home" 
    match '/index2'	=> :index2 
    match '/how' => :how, :as => "how"
    match '/about' => :about, :as => "about"
    match '/price' => :price, :as => "price"
    match '/contact' => :contact, :as => "contact"
    match '/blog' => :blog, :as => "blog"
    match '/guide' => :guide, :as => "guide"
  end

  match '/embed', :controller => :home, :action => :embed
  
  constraints(Subdomain) do  
    match '/', :to => redirect("/customers/sign_in") 
  end  
  
  root :to => "home#index"
  match 'test/' => 'java_script_tests#order'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  include Authable
  belongs_to :round
  belongs_to :supplier
  has_many :orders, :dependent => :destroy
  has_many :regular_orders, :dependent => :destroy
  acts_as_indexed :fields => [:name, :email, :address, :postcode, :telephone]
  before_update :remove_orders, :if => Proc.new { |c| c.round_id_changed? }

  # Include default devise modules. Others available are:
  # :http_authenticatable, :token_authenticatable, :lockable, :timeoutable and :activatable
  devise :database_authenticatable, :recoverable, :invitable,
         :rememberable, :trackable, :validatable

  DEFAULT_PASSWORD = 'fdjaHjk9099kjflkjl'

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :round_id, :supplier_id, :name, :address, :postcode, :telephone
  cattr_reader :per_page
  @@per_page = 8
  
  scope :for_supplier, lambda { |supplier_id| 
    {:conditions => ['supplier_id = ?', supplier_id],
      :order => 'updated_at DESC' }
  }

  def self.search(supplier_id, search)
    if(search.present?)
      for_supplier(supplier_id).with_query('^' + search)
    else
      for_supplier(supplier_id)
    end
  end


  def self.accept_updates(customer_ids)
    return unless customer_ids
    customer_ids.each do |c|
      Customer.find(c).orders.each do |o|
        o.update_attributes(:pending_update => false)
      end
      Customer.find(c).regular_orders.each do |o|
        o.update_attributes(:pending_update => false)
      end
    end
  end
  
  def status
    if(self.invitation_accepted?)
      :active
    elsif(self.invited?)
      :invited
    else
      :new
    end
  end

  def regular_note
    regular_order.note if regular_order
  end

  def regular_order
    regular_orders[0]
  end

  def future_orders
    orders.find_all{|o| o.delivery.last_order > DateTime.now }
  end

  def export_fields
    [round.name, name, address, postcode, telephone] + ((regular_orders[0]) ? [regular_orders[0].note] : [])
  end

  protected
  def password_required?
    !password.nil? || !password_confirmation.nil?
  end
  

  private

  def remove_orders
    logger.info "removing customers orders!"
    orders.each { |o| o.destroy }  if orders
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_filter :authenticate_supplier!, :get_rounds
  
  def index
    @customers = Customer.search(@supplier.id, params[:search]).paginate(:page => params[:page])
  end
  
  def edit
    @customer = Customer.find(params[:id])
    @rounds = Round.for_supplier(@supplier.id)
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(params[:customer])
    @customer.supplier_id = @supplier.id
    @customer.password = Customer::DEFAULT_PASSWORD 
    @customer.password_confirmation = Customer::DEFAULT_PASSWORD 
    if(@customer.save)
      redirect_to customers_path
    else
      render :action => :new
    end
  end

  def invite
    @customer = Customer.find(params[:id])
    @customer.invite!
    flash[:notice] = "Invite sent to #{@customer.email}"
    redirect_to customers_path
  end

  def update
    @customer = Customer.find(params[:id])
    if(@customer.update_attributes(params[:customer]))
       redirect_to customers_path
    else
      render :action => :edit
    end
  end

  def destroy
    @customer = Customer.find_by_id_and_supplier_id(params[:id], @supplier.id)
    @customer.destroy
    flash[:notice] = "Customer #{@customer.name} has been deleted"
    redirect_to customers_path
  end
  
  private 

  def get_rounds
    @rounds = Round.for_supplier(@supplier.id)
  end

end

app/helpers/customers_helper.rb
module CustomersHelper
  def link_to_invitation(customer)
    if(customer.status == :active)
      return
    elsif(customer.status == :new)
      link_to 'Invite', invite_customer_path(customer)
    else
      link_to 'Re-Send Invite', invite_customer_path(customer)
    end
  end
    
end

app/views/customers/_customer_fields.html.haml
-@customer.errors.each do |e|
  %li
    %p=e
%li
  =customer_fields.label :email
  =customer_fields.text_field :email
%li
  =customer_fields.label :name
  =customer_fields.text_field :name
%li
  =customer_fields.label :address
  =customer_fields.text_area :address, :rows => 3
%li
  =customer_fields.label :postcode
  =customer_fields.text_field :postcode
%li
  =customer_fields.label :telephone
  =customer_fields.text_field :telephone
%li
  =customer_fields.label :round_id
  =customer_fields.collection_select(:round_id, @rounds, :id, :name)

app/views/customers/edit.html.haml
=content_for :head do
  :javascript
    $(function(){
      $('#customer_round_id').change(function(){
        alert('If you change the round of this customer any existing changes to the customers regular order will be deleted as these orders are linked to the customers current round');
      })
    })

%h1 Update your customer

=form_for @customer do |f|
  %fieldset
    %ul
      = render :partial => 'customer_fields', :object => f
      %li
        =label_tag ""
        =f.submit 'Update'
        =link_to "Cancel", customers_path

app/views/customers/index.html.haml
#help
  %h2 Tasks
  %ul
    %li=link_to 'Create a new customer', new_customer_path
    %li Invite all new customers
    %li Import new customers
  %h2 Help
  To add a new customer you follow the following steps:
  %ol
    %li Click in the 'Create a new customer' link above
    %li Enter the customer details and select their round
    %li If the customer has an existing order you can add it by clicking on the 'Orders' link
    %li Send the customer an invite by clicking on the 'Invite' link

%h1 Your Customers
=form_tag customers_path, :method => :get do
  %p
    = text_field_tag :search, params[:search], :size => 40
    = submit_tag "Search", :name => nil 

%ul.boxes
  -@customers.each do |c|
    %li
      .box
        %ul
          %li=c.name
          %li=c.email
          %li=c.address
          %li=c.postcode
          %li=c.telephone
          %li Status: #{ c.status.to_s.capitalize }
          %li
            =link_to 'Edit', edit_customer_path(c)
            =link_to 'Orders', customer_orders_path(c)
            =link_to_invitation(c)
            =link_to "Delete", c, :confirm => 'Are you sure you want to delete this customer and all their orders?', :method => :delete 

=will_paginate @customers

app/views/customers/new.html.haml
%h1 Invite a new customer
-if(@rounds.blank?)
  #alert You need to create a round to assign your customer to before you can add customers
-else
  =form_for @customer do |f|
    %fieldset
      %ul
        = render :partial => 'customer_fields', :object => f
        %li
          =label_tag ""
          = f.submit 'Create'