config/routes.rb
Why::Application.routes.draw do
  devise_for :customers
  devise_for :supplier_users
  devise_for :admins

  resources  :supplier_users
  resources :rounds do 
    member do
      get :past
      get :future
    end
    resources  :deliveries do
      collection do
        post :create_all
      end
    end
  end
  resources :products do
    collection do 
      post :reorder
      get :cat
    end
  end
  resources :customers do
    member do
      get :invite
    end
    resources :orders do
      collection do
        get :confirm
        get :past
      end
    end
  end

  resources :suppliers do
    member do
      get :switch
      post :accept
      post :download
      post :labels
    end
  end

  scope :path => '/home', :controller => :home do 
    match '/index'	=> :index, :as => "home" 
    match '/index2'	=> :index2 
    match '/how' => :how, :as => "how"
    match '/about' => :about, :as => "about"
    match '/price' => :price, :as => "price"
    match '/contact' => :contact, :as => "contact"
    match '/blog' => :blog, :as => "blog"
    match '/guide' => :guide, :as => "guide"
  end

  match '/embed', :controller => :home, :action => :embed
  
  constraints(Subdomain) do  
    match '/', :to => redirect("/customers/sign_in") 
  end  
  
  root :to => "home#index"
  match 'test/' => 'java_script_tests#order'

end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
  has_many :rounds
  has_many :products

  validates_presence_of :name
  validates_format_of :parent_url, :with => URI::regexp(%w(http https)), :if => :embed
  validates_format_of :from_email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :allow_nil => true
  has_friendly_id :name, :use_slug => true
  has_attached_file :logo
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_filter :authenticate_admin!, :only => [:index, :new, :create]
  before_filter :authenticate_supplier!, :except => [:index, :new, :create]  

  def index
    @suppliers = Supplier.all
  end

  def new
    @supplier = Supplier.new
    render :action => 'edit'
  end

  def edit
  end

  def create
    Supplier.create!(params[:supplier])
    redirect_to :action => 'index'
  end

  def update
    params[:supplier][:invite] = nil unless(params[:has_invite])
    params[:supplier][:info] = nil unless(params[:has_news])
    params[:supplier][:email_footer] = nil unless(params[:has_footer])
    if(@supplier.update_attributes(params[:supplier]))
      flash[:notice] = "Your settings have been updated"
      redirect_to supplier_path(@supplier)
    else
      render :action => 'edit'
    end
  end

  def show
    @pending = OrderFactory.pending_customers @supplier.id
    @delivery_dates = [['(select)','']] + Delivery.next_dates(@supplier.id, 30).map { |d| [d] } 
  end

  def switch
    redirect_to supplier_url(params[:id], :subdomain => params[:id])
  end

  def accept
    Customer.accept_updates(params[:accept])
    flash[:notice] = "Customer changes have been accepted"
    redirect_to supplier_path(@supplier.id)
  end

  def download
    delivery_ids = Delivery.ids_for_dates(@supplier, 
                                          p_d(params[:one_date]), 
                                          p_d(params[:from_date]), 
                                          p_d(params[:to_date]))
    if delivery_ids.any? then
      return labels(delivery_ids) if params['format'] == 'Labels'
      return produce(delivery_ids) if params['format'] == 'Produce'
      return deliveries(delivery_ids)
    else
      redirect_to supplier_path(@supplier)
    end
  end

  private

  def p_d(d)
    return d unless d.present?
    Date.strptime(d, "%Y-%m-%d")
  end

  def deliveries(delivery_ids)
    send_data Delivery.all_orders_csv(delivery_ids),
      :filename => 'deliveries.csv',
      :type => 'text/csv',
      :disposition => 'attachment'
  end

  def produce(delivery_ids)
    send_data Delivery.all_produce_csv(delivery_ids),
      :filename => 'produce.csv',
      :type => 'text/csv',
      :disposition => 'attachment'
  end

  def labels(delivery_ids)
    pdf = PdfLabelMaker.avery_labels(Delivery.all_orders(delivery_ids))
    send_data pdf.render, 
      :filename => 'labels.pdf', 
      :type => 'application/pdf',
      :disposition => 'attachment'
  end
end

app/views/suppliers/edit.html.haml
:javascript
  $(function(){
    $("#url_li").css('display',$("#supplier_embed").is(":checked") ? 'inherit' : 'none');
    $("#supplier_embed").click(function(){
      if($("#supplier_embed").is(":checked"))
      {
        $("#url_li").slideDown();
      }
      else
      {
        $("#url_li").slideUp();
      }
    });
    why.setupEnableText('#has_invite', '#supplier_invite', '#invite_li');
    why.setupEnableText('#has_news', '#supplier_info', '#news_li');
    why.setupEnableText('#has_footer', '#supplier_email_footer', '#footer_li');
  })
%h1 Update your settings
=form_for @supplier, :html => { :multipart => true } do |f|
  -@supplier.errors.full_messages.each do |e|
    %p.error=e
  %fieldset
    %ul
      %li
        =f.label :name
        =f.text_field :name
      %li
        =f.label :logo
        =f.file_field :logo
      %li
        =label_tag :has_news, 'Show News'
        =check_box_tag :has_news
      %li#news_li
        =f.label :info, 'News' 
        =f.text_area :info, :class => 'editor'
      %li
        =f.label :from_email, 'Address that emails are sent from' 
        =f.text_field :from_email
      %li
        =label_tag :has_invite, 'Customise Invite'
        =check_box_tag :has_invite
      %li#invite_li
        =f.label :invite, 'Custom Invite Text'
        =f.text_area :invite, :class => 'editor'
      %li
        =label_tag :has_footer, 'Add an email footer'
        =check_box_tag :has_footer
      %li#footer_li
        =f.label :email_footer, 'Email Footer (shown on invite and confirmation email)'
        =f.text_area :email_footer, :class => 'editor'
      %li
        =f.label :embed, 'Embed in your own website'
        =f.check_box :embed
      %li#url_li
        =f.label :parent_url
        =f.text_field :parent_url
      %li
        =label_tag ''
        =submit_tag 'Update', :class => 'wymupdate'

app/views/suppliers/index.html.haml
%ol
  -@suppliers.each do |s|
    %li
      =link_to s.name, switch_supplier_path(s)
      =link_to 'edit', edit_supplier_path(s)
  %li=link_to 'New', new_supplier_path

app/views/suppliers/show.html.haml
#help
  %h2 Tasks
  =form_tag download_supplier_path do
    %ul
      %li
        For deliveries on 
        =select nil,'one_date', @delivery_dates
      %li
        or between
        %br
        =select nil,'from_date', @delivery_dates
        and 
        =select nil,'to_date', @delivery_dates
      %li
        download your
        %br
        =submit_tag 'Deliveries', {:name => 'format', :value => 'Deliveries' }
        =submit_tag 'Produce', {:name => 'format', :value => 'Produce' }
        or
        =submit_tag 'Labels', {:name => 'format', :value => 'Labels' }

%h1 
  Customer Order Changes
#deliveries
  =form_tag accept_supplier_path do
    =submit_tag 'clear updates'
    .customer
      -@pending.each do |c, orders|
        =check_box_tag 'accept[]', c.id
        %h3.customer_details=[c.name ,c.email ,c.address ,c.postcode ,c.telephone].reject{|a| a.blank?}.join(', ')
        %ul
          -orders.each do |order|
            %li
              .order{:class =>  order.respond_to?(:delivery) ? '':'regularOrder'}
                -if order.respond_to?(:delivery)
                  %h3=order.delivery.date.to_s(:short)
                -else
                  %h3 Regular Order
                %ul
                  -order.items.each do |item|
                    %li
                      =item.quantity
                      =' x '
                      =item.product.name
                      -if item.respond_to?(:frequency)
                        every
                        =item.frequency
                        week(s) from
                        =item.first_delivery_date.to_s(:short)
                  -if order.note.present?
                    %li
                      %em
                        Note: 
                        =order.note
              