config/routes.rb
Why::Application.routes.draw do
  devise_for :customers
  devise_for :supplier_users
  devise_for :admins

  resources  :supplier_users
  resources :rounds do 
    member do
      get :past
      get :future
    end
    resources  :deliveries do
      collection do
        post :create_all
      end
    end
  end
  resources :products do
    collection do 
      post :reorder
      get :cat
    end
  end
  resources :customers do
    member do
      get :invite
    end
    resources :orders do
      collection do
        get :confirm
        get :past
      end
    end
  end

  resources :suppliers do
    member do
      get :switch
      post :accept
      post :download
      post :labels
    end
  end

  scope :path => '/home', :controller => :home do 
    match '/index'	=> :index, :as => "home" 
    match '/index2'	=> :index2 
    match '/how' => :how, :as => "how"
    match '/about' => :about, :as => "about"
    match '/price' => :price, :as => "price"
    match '/contact' => :contact, :as => "contact"
    match '/blog' => :blog, :as => "blog"
    match '/guide' => :guide, :as => "guide"
  end

  match '/embed', :controller => :home, :action => :embed
  
  constraints(Subdomain) do  
    match '/', :to => redirect("/customers/sign_in") 
  end  
  
  root :to => "home#index"
  match 'test/' => 'java_script_tests#order'

end

app/views/layouts/application.html.haml
-title()
!!! 5
%html
  %head
    %title=yield :title
    =hoptoad_javascript_notifier
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.8.1/build/reset/reset-min.css">
    =stylesheet_link_tag :all
    =javascript_include_tag :defaults, 'jquery.autocomplete', 'jquery-ui','myga','wymeditor/jquery.wymeditor.min.js'
    <script type="text/javascript" src="http://use.typekit.com/rjk6gwu.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
    <meta name="keywords" content="food, producer, orders, delivery, organic, application, supplier" />
    <meta name="description" content="An Order Management System for Local Food Suppliers"/>
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
    = csrf_meta_tag
    =yield :head
  %body{ :id => tab_name }
    #header
      #logo
        =yield :logo
      #menu
        %ul
          %li=link_to 'Sign Out Admin', destroy_admin_session_path if admin_signed_in?
          %li=link_to 'Sign Out Supplier', destroy_supplier_user_session_path if supplier_user_signed_in?
          %li=link_to 'Sign Out Customer', destroy_customer_session_path if customer_signed_in?
    #navigation
      %ul
        -if admin_signed_in?
          %li#suppliers_tab=link_to 'Suppliers', suppliers_path
        -if (supplier_user_signed_in? || admin_signed_in?) && @supplier && !@supplier.new_record?
          %li#dashboard_tab=link_to 'Dashboard', supplier_path(@supplier), { :accesskey => '1'}
          %li#customers_tab=link_to 'Customers', customers_path, { :accesskey => 2}
          %li#products_tab=link_to 'Products', products_path, { :accesskey => 3}
          %li#rounds_tab=link_to 'Rounds', rounds_path, { :accesskey => 4}
          %li#users_tab=link_to 'Team', supplier_users_path, { :accesskey => 5}
          %li#settings_tab=link_to 'Settings', edit_supplier_path(@supplier), { :accesskey => 6}
          %li#guide_tab=link_to 'Guide',guide_path, { :accesskey => 7}
    %hr.navcon
    #content
      -if(flash[:notice])
        #notice=flash[:notice]
      -if(flash[:alert])
        #alert=flash[:alert]
      =yield

app/views/layouts/embed.html.haml
-title()
!!! 5
%html
  %head
    %title=yield :title
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.8.1/build/reset/reset-min.css">
    =stylesheet_link_tag :all
    =javascript_include_tag :defaults, 'jquery.autocomplete', 'jquery-ui','myga','wymeditor/jquery.wymeditor.min.js'
    <script type="text/javascript" src="http://use.typekit.com/rjk6gwu.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
    <meta name="keywords" content="food, producer, orders, delivery, organic, application, supplier" />
    <meta name="description" content="An Order Management System for Local Food Suppliers"/>
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
    = csrf_meta_tag
    =yield :head
  %body{ :id => tab_name }
    #content
      -if(flash[:notice])
        #notice=flash[:notice]
      -if(flash[:alert])
        #alert=flash[:alert]
      =link_to 'Sign Out', destroy_customer_session_path if customer_signed_in?
      =yield

app/views/layouts/home.html.haml
!!! 5
%html
  %head
    <meta name="google-site-verification" content="FUM3w02GCAyjArGC1COWF7vohaUDhM02bDEUtX67YbM" />
    %title="#{ tab_name.capitalize } - We like our food to come - From Where It's Grown"
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.8.1/build/reset/reset-min.css">
    =stylesheet_link_tag :all
    <script type="text/javascript" src="http://use.typekit.com/rjk6gwu.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
    =javascript_include_tag 'myga'
    <meta name="keywords" content="food, producer, orders, delivery, organic, application, supplier" />
    <meta name="description" content="An Order Management System for Local Food Suppliers"/>
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
    = csrf_meta_tag
    =yield :head
  %body.promo{ :id => tab_name }
    #navigation
      -if tab_name != 'index' then
        =image_tag 'logo.gif'
      %ul
        %li#home_tab=link_to 'Home', home_path
        %li#how_tab=link_to 'How', how_path
        %li#price_tab=link_to 'Pricing', price_path
        %li#about_tab=link_to 'About us', about_path
        %li#blog_tab=link_to 'Blog', blog_path
        %li#contact_tab=link_to 'Contact Us', contact_path
    %hr.navcon
    #content
      -if(flash[:notice])
        #notice=flash[:notice]
      -if(flash[:alert])
        #alert=flash[:alert]
      .inner
        =yield
      #footer 
        <a href="http://www.twitter.com/fromwhereitsgro"><img src="http://twitter-badges.s3.amazonaws.com/follow_us-b.png" alt="Follow fromwhereitsgro on Twitter"/></a>
        %br
        Design by
        %a{ :href => 'mailto:tom@fromwhereitsgrown.com'} Tom
        Cartoon by
        %a{ :href => 'mailto:sammyborras@gmail.com'} Sammy Borras